/*
  NEXUS 360 — Schema and Table DDL
  Database: SFK_HACKATHON
  Schema:   SFK_HACK_1
  Warehouse: SHAN_WH
*/

USE WAREHOUSE SHAN_WH;
USE DATABASE SFK_HACKATHON;

CREATE SCHEMA IF NOT EXISTS SFK_HACK_1;
USE SCHEMA SFK_HACK_1;

-- 1. CUSTOMER
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    EMAIL               VARCHAR(200),
    PHONE               VARCHAR(30),
    DATE_OF_BIRTH       DATE,
    GENDER              VARCHAR(10),
    SEGMENT             VARCHAR(50),
    REGION              VARCHAR(50),
    STATE               VARCHAR(50),
    CITY                VARCHAR(100),
    ZIP_CODE            VARCHAR(10),
    TENURE_MONTHS       INTEGER,
    LIFETIME_VALUE      FLOAT,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);

-- 2. POLICY
CREATE OR REPLACE TABLE POLICY (
    POLICY_ID           VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    POLICY_TYPE         VARCHAR(50),
    PREMIUM_AMOUNT      FLOAT,
    START_DATE          DATE,
    END_DATE            DATE,
    STATUS              VARCHAR(20),
    COVERAGE_AMOUNT     FLOAT,
    DEDUCTIBLE          FLOAT,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (POLICY_ID)
);

-- 3. CLAIM
CREATE OR REPLACE TABLE CLAIM (
    CLAIM_ID            VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    POLICY_ID           VARCHAR(20),
    CLAIM_TYPE          VARCHAR(50),
    CLAIM_AMOUNT        FLOAT,
    STATUS              VARCHAR(20),
    FILED_DATE          DATE,
    RESOLVED_DATE       DATE,
    RESOLUTION_DAYS     INTEGER,
    DESCRIPTION         VARCHAR(1000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_ID)
);

-- 4. PAYMENT
CREATE OR REPLACE TABLE PAYMENT (
    PAYMENT_ID          VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    POLICY_ID           VARCHAR(20),
    AMOUNT              FLOAT,
    PAYMENT_DATE        DATE,
    DUE_DATE            DATE,
    STATUS              VARCHAR(20),
    PAYMENT_METHOD      VARCHAR(30),
    FAILURE_REASON      VARCHAR(200),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PAYMENT_ID)
);

-- 5. INTERACTION
CREATE OR REPLACE TABLE INTERACTION (
    INTERACTION_ID      VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    CHANNEL             VARCHAR(30),
    DIRECTION           VARCHAR(20),
    INTERACTION_DATE    TIMESTAMP_NTZ,
    DURATION_SECONDS    INTEGER,
    AGENT_ID            VARCHAR(20),
    DISPOSITION         VARCHAR(50),
    TOPIC               VARCHAR(100),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (INTERACTION_ID)
);

-- 6. TRANSCRIPT
CREATE OR REPLACE TABLE TRANSCRIPT (
    TRANSCRIPT_ID       VARCHAR(20)   NOT NULL,
    INTERACTION_ID      VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    TRANSCRIPT_TEXT     VARCHAR(16777216),
    SPEAKER_LABELS      VARIANT,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TRANSCRIPT_ID)
);

-- 7. EMAIL
CREATE OR REPLACE TABLE EMAIL (
    EMAIL_ID            VARCHAR(20)   NOT NULL,
    INTERACTION_ID      VARCHAR(20),
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    SUBJECT             VARCHAR(500),
    BODY                VARCHAR(16777216),
    DIRECTION           VARCHAR(20),
    SENT_AT             TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EMAIL_ID)
);

-- 8. NOTE
CREATE OR REPLACE TABLE NOTE (
    NOTE_ID             VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    INTERACTION_ID      VARCHAR(20),
    AGENT_ID            VARCHAR(20),
    NOTE_TEXT           VARCHAR(16777216),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (NOTE_ID)
);

-- 9. SURVEY
CREATE OR REPLACE TABLE SURVEY (
    SURVEY_ID           VARCHAR(20)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    SURVEY_TYPE         VARCHAR(50),
    NPS_SCORE           INTEGER,
    CSAT_SCORE          INTEGER,
    COMMENTS            VARCHAR(2000),
    SUBMITTED_AT        TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SURVEY_ID)
);

-- 10. CUSTOMER_EVENT
CREATE OR REPLACE TABLE CUSTOMER_EVENT (
    EVENT_ID            VARCHAR(30)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    EVENT_TYPE          VARCHAR(50),
    EVENT_TIMESTAMP     TIMESTAMP_NTZ,
    SOURCE_TABLE        VARCHAR(50),
    SOURCE_ID           VARCHAR(20),
    EVENT_PAYLOAD       VARIANT,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
);

-- 11. CUSTOMER_MOMENT
CREATE OR REPLACE TABLE CUSTOMER_MOMENT (
    MOMENT_ID           VARCHAR(30)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    MOMENT_TYPE         VARCHAR(50),
    DETECTED_AT         TIMESTAMP_NTZ,
    CONFIDENCE          FLOAT,
    CONTEXT             VARIANT,
    SOURCE_EVENT_ID     VARCHAR(30),
    EXPIRES_AT          TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MOMENT_ID)
);

-- 12. CUSTOMER_HEALTH
CREATE OR REPLACE TABLE CUSTOMER_HEALTH (
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    HEALTH_SCORE        FLOAT,
    CHURN_RISK          FLOAT,
    SENTIMENT_SCORE     FLOAT,
    CLAIMS_SCORE        FLOAT,
    PAYMENT_SCORE       FLOAT,
    ENGAGEMENT_SCORE    FLOAT,
    RISK_LEVEL          VARCHAR(20),
    SCORED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);

-- 13. NEXT_BEST_ACTION
CREATE OR REPLACE TABLE NEXT_BEST_ACTION (
    ACTION_ID           VARCHAR(50)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    ACTION_TYPE         VARCHAR(50),
    CONFIDENCE          FLOAT,
    RATIONALE           VARCHAR(2000),
    PRIORITY            INTEGER,
    STATUS              VARCHAR(20) DEFAULT 'PENDING',
    SUPPRESSED          BOOLEAN DEFAULT FALSE,
    SUPPRESSION_REASON  VARCHAR(500),
    EVIDENCE            VARIANT,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT          TIMESTAMP_NTZ,
    PRIMARY KEY (ACTION_ID)
);

-- 14. NEXT_BEST_ACTION_LOG
CREATE OR REPLACE TABLE NEXT_BEST_ACTION_LOG (
    LOG_ID              VARCHAR(80)   NOT NULL,
    ACTION_ID           VARCHAR(50)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    ACTION_TYPE         VARCHAR(50),
    DECISION            VARCHAR(20),
    DECIDED_BY          VARCHAR(100),
    DECIDED_AT          TIMESTAMP_NTZ,
    OUTCOME             VARCHAR(50),
    OUTCOME_DATE        TIMESTAMP_NTZ,
    NOTES               VARCHAR(2000),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LOG_ID)
);

-- 15. CUSTOMER_AI_ENRICHMENT
CREATE OR REPLACE TABLE CUSTOMER_AI_ENRICHMENT (
    ENRICHMENT_ID       VARCHAR(30)   NOT NULL,
    CUSTOMER_ID         VARCHAR(20)   NOT NULL,
    SOURCE_TABLE        VARCHAR(50),
    SOURCE_ID           VARCHAR(20),
    SENTIMENT_SCORE     FLOAT,
    SENTIMENT_LABEL     VARCHAR(20),
    ENTITIES            VARIANT,
    INTENTS             VARIANT,
    CLASSIFICATION      VARCHAR(50),
    SUMMARY             VARCHAR(5000),
    ENRICHED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ENRICHMENT_ID)
);
