/*
  NEXUS 360 — Cortex Search Service
  Unified evidence view + search service for evidence retrieval
*/

USE WAREHOUSE SHAN_WH;
USE DATABASE SFK_HACKATHON;
USE SCHEMA SFK_HACK_1;

----------------------------------------------------------------------
-- 1. Unified Evidence View
----------------------------------------------------------------------
CREATE OR REPLACE VIEW EVIDENCE_SOURCE AS
SELECT
    'TRN-' || T.TRANSCRIPT_ID AS DOC_ID,
    T.CUSTOMER_ID,
    'TRANSCRIPT' AS SOURCE_TYPE,
    T.TRANSCRIPT_TEXT AS CONTENT,
    COALESCE(E.SENTIMENT_LABEL, 'UNKNOWN') AS SENTIMENT,
    COALESCE(E.CLASSIFICATION, 'UNCLASSIFIED') AS MOMENT_TYPE,
    T.CREATED_AT AS EVENT_DATE
FROM TRANSCRIPT T
LEFT JOIN CUSTOMER_AI_ENRICHMENT E
    ON T.TRANSCRIPT_ID = E.SOURCE_ID AND E.SOURCE_TABLE = 'TRANSCRIPT'

UNION ALL

SELECT
    'EML-' || EM.EMAIL_ID AS DOC_ID,
    EM.CUSTOMER_ID,
    'EMAIL' AS SOURCE_TYPE,
    EM.SUBJECT || ': ' || EM.BODY AS CONTENT,
    COALESCE(E.SENTIMENT_LABEL, 'UNKNOWN') AS SENTIMENT,
    COALESCE(E.CLASSIFICATION, 'UNCLASSIFIED') AS MOMENT_TYPE,
    EM.SENT_AT AS EVENT_DATE
FROM EMAIL EM
LEFT JOIN CUSTOMER_AI_ENRICHMENT E
    ON EM.EMAIL_ID = E.SOURCE_ID AND E.SOURCE_TABLE = 'EMAIL'

UNION ALL

SELECT
    'NTE-' || N.NOTE_ID AS DOC_ID,
    N.CUSTOMER_ID,
    'NOTE' AS SOURCE_TYPE,
    N.NOTE_TEXT AS CONTENT,
    'UNKNOWN' AS SENTIMENT,
    'UNCLASSIFIED' AS MOMENT_TYPE,
    N.CREATED_AT AS EVENT_DATE
FROM NOTE N

UNION ALL

SELECT
    'SRV-' || S.SURVEY_ID AS DOC_ID,
    S.CUSTOMER_ID,
    'SURVEY' AS SOURCE_TYPE,
    S.SURVEY_TYPE || ' Survey (NPS: ' || S.NPS_SCORE || ', CSAT: ' || S.CSAT_SCORE || '): ' || COALESCE(S.COMMENTS, '') AS CONTENT,
    CASE
        WHEN S.NPS_SCORE >= 9 THEN 'POSITIVE'
        WHEN S.NPS_SCORE <= 6 THEN 'NEGATIVE'
        ELSE 'NEUTRAL'
    END AS SENTIMENT,
    'UNCLASSIFIED' AS MOMENT_TYPE,
    S.SUBMITTED_AT AS EVENT_DATE
FROM SURVEY S;

----------------------------------------------------------------------
-- 2. Cortex Search Service
----------------------------------------------------------------------
CREATE OR REPLACE CORTEX SEARCH SERVICE NEXUS360_EVIDENCE_SEARCH
    ON CONTENT
    ATTRIBUTES CUSTOMER_ID, SOURCE_TYPE, SENTIMENT, MOMENT_TYPE
    WAREHOUSE = SHAN_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT
        DOC_ID,
        CUSTOMER_ID,
        SOURCE_TYPE,
        CONTENT,
        SENTIMENT,
        MOMENT_TYPE,
        EVENT_DATE
    FROM EVIDENCE_SOURCE
);
